### ISSUE TITLE
Use Text commands as default when no command type is specified

### ISSUE THREAD

**Issue by pawap90** [pawap90/acho-bot#16]
When creating a new dynamic command, if no Command type is specified, use "Text" by default. This will allow users to leave the "Type" column empty in Notion.

**Comment by pawap90** [comment]
I think this can be fixed in `notion-commands.loader.ts` by setting the type as Text when no value is provided before calling `createCommandInstance`

**Comment by justinhhorner** [comment]
I'll work on this tomorrow on stream. I ran out of time today. 😅
